name: foo

defaults:
  local: ../package-defaults.yaml

library:
  source-dirs: library

executables:
  bar-exe:
    main: Main.hs
    source-dirs: executables
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: foo
